name = "asadul-portfolio"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[build.upload]
format = "modules"
dir = ".next"

[[env.production]]
name = "asadul-portfolio"
route = "asadul.dev/*"

[[env.staging]]
name = "asadul-portfolio-staging"
route = "staging.asadul.dev/*"
